import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // 使用Docusaurus自动生成侧边栏功能，根据文件夹结构生成分类
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: ".", // 从docs文件夹自动生成侧边栏
    },
  ],
};

// Use autogenerated sidebars and category positions for correct prev/next order
export default sidebars;
