import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // 显式定义：将首页文档置顶，其余按照指定目录顺序自动生成
  tutorialSidebar: [
    { type: "doc", id: "index" },
    {
      type: "category",
      label: "Getting Started",
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Deployment",
      items: [{ type: "autogenerated", dirName: "deployment" }],
    },
    {
      type: "category",
      label: "Configuration",
      items: [{ type: "autogenerated", dirName: "configuration" }],
    },
    {
      type: "category",
      label: "Advanced Guides",
      items: [{ type: "autogenerated", dirName: "advanced-guides" }],
    },
    {
      type: "category",
      label: "Billing",
      items: [{ type: "autogenerated", dirName: "billing" }],
    },
    { type: "doc", id: "web-sdk" },
    {
      type: "category",
      label: "Support",
      items: [{ type: "autogenerated", dirName: "support" }],
    },
  ],
};

export default sidebars;
