apiVersion: v1
kind: Service
metadata:
  name: saas-doc
  namespace: production
spec:
  selector:
    app: saas-doc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-doc-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saas-doc
  template:
    metadata:
      labels:
        app: saas-doc
    spec:
      containers:
      - name: saas-doc
        image: ocir.us-sanjose-1.oci.oraclecloud.com/axqjl8ow85vi/saas-doc:v0.0.31
        ports:
        - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: doc-ingress
  namespace: production
spec:
  ingressClassName: nginx
  rules:
    - host: doc.softprobe.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-doc
                port:
                  number: 80
    - host: docs.softprobe.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-doc
                port:
                  number: 80
    - host: document.softprobe.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-doc
                port:
                  number: 80
