name: Docker Image CI

on:
  release:
    types: [published]

env:
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: us-sanjose-1
  IMAGE_TAG: ${{ github.event.release.tag_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to OCI Registry
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Get or create an OCIR Repository
        uses: oracle-actions/get-ocir-repository@v1.3.0
        id: get-ocir-repository
        with:
          name: saas-doc
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
    
      - name: Tag and push a container image
        id: tag-and-push-image
        run: |
          docker build . -t "${{ steps.get-ocir-repository.outputs.repo_path }}:${{ env.IMAGE_TAG }}"
          docker push "${{ steps.get-ocir-repository.outputs.repo_path }}:${{ env.IMAGE_TAG }}"
          # print the full image path
          echo "Pushed image to ${{ steps.get-ocir-repository.outputs.repo_path }}:${{ env.IMAGE_TAG }}"
          echo "Note: Container exposes port 80. Make sure your service maps to 80 externally."
